// tag browser
// tag list
export const FETCH_TAGS_LIST = 'FETCH_TAGS_LIST'
export const FETCH_TAGS_LIST_SUCCESS = 'FETCH_TAGS_LIST_SUCCESS'
export const FETCH_TAGS_LIST_FAILED = 'FETCH_TAGS_LIST_FAILED'

// tag list item current value
export const FETCH_TAGS_LIST_ITEM_CURRENT_VALUE = 'FETCH_TAGS_LIST_ITEM_CURRENT_VALUE'
export const FETCH_TAGS_LIST_ITEM_CURRENT_VALUE_SUCCESS = 'FETCH_TAGS_LIST_ITEM_CURRENT_VALUE_SUCCESS'
export const FETCH_TAGS_LIST_ITEM_CURRENT_VALUE_FAILED = 'FETCH_TAGS_LIST_ITEM_CURRENT_VALUE_FAILED'
// tag list item 1 hr spark line data
export const FETCH_TAGS_LIST_ITEM_ONEHOUR_SPARKLINE = 'FETCH_TAGS_LIST_ITEM_ONEHOUR_SPARKLINE'
export const FETCH_TAGS_LIST_ITEM_ONEHOUR_SPARKLINE_SUCCESS = 'FETCH_TAGS_LIST_ITEM_ONEHOUR_SPARKLINE_SUCCESS'
export const FETCH_TAGS_LIST_ITEM_ONEHOUR_SPARKLINE_FAILED = 'FETCH_TAGS_LIST_ITEM_ONEHOUR_SPARKLINE_FAILED'
// tag list item 1 hr average
export const FETCH_TAGS_LIST_ITEM_ONEHOUR_AVERAGE = 'FETCH_TAGS_LIST_ITEM_ONEHOUR_AVERAGE'
export const FETCH_TAGS_LIST_ITEM_ONEHOUR_AVERAGE_SUCCESS = 'FETCH_TAGS_LIST_ITEM_ONEHOUR_AVERAGE_SUCCESS'
export const FETCH_TAGS_LIST_ITEM_ONEHOUR_AVERAGE_FAILED = 'FETCH_TAGS_LIST_ITEM_ONEHOUR_AVERAGE_FAILED'
// tag list item 24 hr / 1 day average
export const FETCH_TAGS_LIST_ITEM_ONEDAY_AVERAGE = 'FETCH_TAGS_LIST_ITEM_ONEDAY_AVERAGE'
export const FETCH_TAGS_LIST_ITEM_ONEDAY_AVERAGE_SUCCESS = 'FETCH_TAGS_LIST_ITEM_ONEDAY_AVERAGE_SUCCESS'
export const FETCH_TAGS_LIST_ITEM_ONEDAY_AVERAGE_FAILED = 'FETCH_TAGS_LIST_ITEM_ONEDAY_AVERAGE_FAILED'

// tag details
// set timeperiod opted
export const SET_TIME_PERIOD_OPTED = 'SET_TIME_PERIOD_OPTED'

//meta data
export const FETCH_TAG_META_DATA = 'FETCH_TAG_META_DATA'
export const FETCH_TAG_META_DATA_SUCCESS = 'FETCH_TAG_META_DATA_SUCCESS'
export const FETCH_TAG_META_DATA_FAILED = 'FETCH_TAG_META_DATA_FAILED'

// current details
// value
export const FETCH_TAG_CURRENT_VALUE = 'FETCH_TAG_CURRENT_VALUE'
export const FETCH_TAG_CURRENT_VALUE_SUCCESS = 'FETCH_TAG_CURRENT_VALUE_SUCCESS'
export const FETCH_TAG_CURRENT_VALUE_FAILED = 'FETCH_TAG_CURRENT_VALUE_FAILED'
//average 
export const FETCH_TAG_CURRENT_AVERAGE = 'FETCH_TAG_CURRENT_AVERAGE'
export const FETCH_TAG_CURRENT_AVERAGE_SUCCESS = 'FETCH_TAG_CURRENT_AVERAGE_SUCCESS'
export const FETCH_TAG_CURRENT_AVERAGE_FAILED = 'FETCH_TAG_CURRENT_AVERAGE_FAILED'

//tag histogram data
export const FETCH_TAG_HISTOGRAM_DATA = 'FETCH_TAG_HISTOGRAM_DATA'
export const FETCH_TAG_HISTOGRAM_DATA_SUCCESS = 'FETCH_TAG_HISTOGRAM_DATA_SUCCESS'
export const FETCH_TAG_HISTOGRAM_DATA_FAILED = 'FETCH_TAG_HISTOGRAM_DATA_FAILED'

//tag heatmap data
export const FETCH_TAG_HEATMAP_DATA = 'FETCH_TAG_HEATMAP_DATA'
export const FETCH_TAG_HEATMAP_DATA_SUCCESS = 'FETCH_TAG_HEATMAP_DATA_SUCCESS'
export const FETCH_TAG_HEATMAP_DATA_FAILED = 'FETCH_TAG_HEATMAP_DATA_FAILED'